## Projeto Prático - Data App

In [1]:
# JSON Pt.2
import pandas as pd
import json

In [2]:
dados_dict = {
    "nome" : ["Ana", "Bruno", "Carla"],
    "idade" : [25, 30, 22],
    "cidade" : ["São Paulo", "Rio de Janeiro", "Curitiba"]
}

In [3]:
with open ('json_data.json', 'w', encoding="utf-8") as file:
    json.dump(dados_dict, file, ensure_ascii=False, indent=4)

In [4]:
with open('json_data.json', 'r', encoding="utf-8") as file:
    dados_python = json.load(file)

In [5]:
print(dados_python)
type(dados_python)

{'nome': ['Ana', 'Bruno', 'Carla'], 'idade': [25, 30, 22], 'cidade': ['São Paulo', 'Rio de Janeiro', 'Curitiba']}

dict

In [7]:
# Abordagem A: pd.dataframe
df_opcao_a = pd.DataFrame(dados_python)
df_opcao_a

    nome  idade          cidade
0    Ana     25       São Paulo
1  Bruno     30  Rio de Janeiro
2  Carla     22        Curitiba

In [8]:
# Abordagem B: read_json
df_opcao_b = pd.read_json('json_data.json')
df_opcao_b

    nome  idade          cidade
0    Ana     25       São Paulo
1  Bruno     30  Rio de Janeiro
2  Carla     22        Curitiba

In [9]:
df_opcao_b.to_csv('usuario.csv', index=False, encoding="utf-8")

### CSV to JSON

In [10]:
dados = {
    "id" : [1, 2, 3],
    "nome" : ["Bruno", "Silvio", "Carla"],
    "cargo" : ["Analista", "Desenvolvedor", "Gerente"],
    "salario" : [4500, 6200, 9500]
}

df_original = pd.DataFrame(dados)
df_original

   id    nome          cargo  salario
0   1   Bruno       Analista     4500
1   2  Silvio  Desenvolvedor     6200
2   3   Carla        Gerente     9500

In [11]:
df_original.to_csv("dados_exemplo.csv", index=False, encoding="utf-8")

In [12]:
df_original.to_json(
    "dados_output.json", 
    orient="records",
    indent=4,
    force_ascii=False
)

In [13]:
df_original.to_json(
    "dados_output2.json", 
    orient="columns",
    indent=4,
    force_ascii=False
)

In [14]:
df_original.to_json(
    "dados_output3.json", 
    orient="table",
    indent=4,
    force_ascii=False
)